import { Suspense } from 'react';
import { appConfig } from '../config';
import type { MediaProps } from '../utils/types';
import { WeddingGallery } from '@/components/WeddingGallery';
import { storage } from '../storage';

export const revalidate = 60;

/**
 * Fetches wedding media from the configured storage provider with metadata.
 *
 * This function retrieves media from the configured storage provider (Cloudinary or S3).
 * Blur placeholders are generated by the storage service during list().
 *
 * Note: Server-side fetching always shows all media. Guest isolation
 * filtering only applies to client-side API calls.
 *
 * @returns Promise that resolves to an array of processed media data
 * @throws {Error} If storage service fails or environment variables are missing
 */
async function fetchWeddingMedia(): Promise<MediaProps[]> {
  try {
    // Get all media without guest filtering for server-side rendering
    // Blur placeholders are handled by the storage service
    return await storage.list();
  } catch (error) {
    console.error('Failed to fetch wedding media:', error);
    throw new Error('Unable to load wedding media. Please try again later.');
  }
}

/**
 * Home page component that displays the wedding media gallery or name input form.
 *
 * This page serves as the main entry point for the wedding memories application.
 * It uses a client component to conditionally render either the name input form
 * or the media gallery based on whether the guest name is set.
 *
 * @returns JSX element containing the media gallery with integrated modal or name input form
 */
export default async function WeddingMediaHomePage() {
  // If guest isolation is enabled, start with empty array to let client-side filtering handle it
  const weddingMedia = appConfig.guestIsolation ? [] : await fetchWeddingMedia();

  return (
    <Suspense
      fallback={
        <div className="flex items-center justify-center min-h-[50vh]">
          <div className="animate-spin rounded-full h-8 w-8 border-2 border-primary border-t-transparent" />
        </div>
      }
    >
      <WeddingGallery initialMedia={weddingMedia} />
    </Suspense>
  );
}
